#!/bin/bash
# test_qos.sh
# Run this INSIDE Mininet using: sh test_qos.sh
# OR paste commands manually into xterm windows

echo "========================================"
echo "  SCENARIO 1: Baseline connectivity"
echo "========================================"
echo "Run in Mininet CLI:"
echo "  mininet> pingall"
echo "  mininet> h1 ping -c 5 10.0.0.4"
echo "  mininet> h2 ping -c 5 10.0.0.4"
echo ""
echo "Expected: 0% packet loss, ~9ms latency"
echo ""

echo "========================================"
echo "  SCENARIO 2: QoS under congestion"
echo "========================================"
echo "Step 1 - open xterm windows:"
echo "  mininet> xterm h1 h2 h4"
echo ""
echo "Step 2 - in h4 xterm (start servers):"
echo "  iperf -s &"
echo "  iperf -s -u &"
echo ""
echo "Step 3 - in h2 xterm (flood the bottleneck):"
echo "  iperf -c 10.0.0.4 -t 60 -b 45M &"
echo ""
echo "Step 4 - in h1 xterm (high priority stream):"
echo "  iperf -c 10.0.0.4 -u -b 10M -t 30"
echo ""
echo "Step 5 - back in Mininet CLI (measure latency):"
echo "  mininet> h1 ping -c 20 10.0.0.4"
echo "  mininet> h2 ping -c 20 10.0.0.4"
echo ""
echo "Expected: h1 avg ~9ms  |  h2 avg ~50ms+"
echo ""

echo "========================================"
echo "  PROOF COMMANDS (screenshot these)"
echo "========================================"
echo "  mininet> sh ovs-ofctl dump-flows s1"
echo "  mininet> sh ovs-vsctl list Queue"
echo "  mininet> sh ovs-ofctl dump-ports s1"
echo "  mininet> sh ovs-vsctl list QoS"
